#blank_issues_enabled: false
#contact_links:
#  - name: Ask the community for help
#    url: https://github.com/cotes2020/jekyll-theme-chirpy/discussions
#    about: Please ask and answer questions here.
blank_issues_enabled: true
contact_links:
  - name: Bug Report
    url: https://github.com/woori04/woori04.github.io/issues/new?template=bug_report.yml
    about: Report a bug
  - name: Feature Request
    url: https://github.com/woori04/woori04.github.io/issues/new?template=feature_request.yml
    about: Suggest a new feature
